### PR TITLE
Better handling of IO errors

### LINKED ISSUE #511: cohttp server crash when client dies mid-transfer
The following server will crash (usually) if the `wrk` process is canceled with a `ctrl-c`.  I've seen at least `EPIPE`, `ECONNRESET`, `EPROTOTYPE` errors while testing this.

This may be related to #503

Using OCaml 4.02.3, cohttp 0.21.0.  Tested on 64bit OSX and Linux with `libev`/`conf-libev` installed.

Server code:

```ocaml
module Server = Cohttp_lwt_unix.Server

let callback _conn _req body =
  let%lwt body = Cohttp_lwt_body.to_string body in
  Server.respond_string ~status:`OK ~body ()

let server port =
  Server.create ~mode:(`TCP (`Port port)) (Server.make ~callback ())

let () =
  Lwt_engine.set (new Lwt_engine.libev);
  Lwt_main.run (server (int_of_string Sys.argv.(1)))
```

Client using `wrk`:
```
wrk -s put.lua 'http://127.0.0.1:8080/'
```

The `put.lua` script creates a blob of bytes to send as a `PUT` request to the server.

`put.lua`:
```lua
local Chars = {}
for Loop = 0, 255 do
   Chars[Loop+1] = string.char(Loop)
end
local String = table.concat(Chars)

local Built = {['.'] = Chars}

local AddLookup = function(CharSet)
   local Substitute = string.gsub(String, '[^'..CharSet..']', '')
   local Lookup = {}
   for Loop = 1, string.len(Substitute) do
       Lookup[Loop] = string.sub(Substitute, Loop, Loop)
   end
   Built[CharSet] = Lookup

   return Lookup
end

function string.random(Length, CharSet)
   -- Length (number)
   -- CharSet (string, optional); e.g. %l%d for lower case letters and digits

   local CharSet = CharSet or '.'

   if CharSet == '' then
      return ''
   else
      local Result = {}
      local Lookup = Built[CharSet] or AddLookup(CharSet)
      local Range = table.getn(Lookup)

      for Loop = 1,Length do
         Result[Loop] = Lookup[math.random(1, Range)]
      end

      return table.concat(Result)
   end
end

wrk.method = "PUT"
wrk.body   = string.random(1000000, "%l%d")
wrk.headers["Content-Type"] = "text/plain"
```

### PR DESCRIPTION
**Pull request by talex5**
Before, if the client closed the connection while we were handling a request, the server would crash (by default, unless the user overrode that using `on_exn` or changing `Lwt`'s async exception handler). Now, we just log this at `info` level and continue. Exceptions produced by user code are logged as errors, while other exceptions generated by cohttp call back to the conduit exception handler, as before.

Fixes #511.

I first tried getting the IO operations to return a `result` and plumbing that through everywhere, but it was very painful and caused lots of API changes. So instead, each IO monad is now expected to include handling of IO errors, and provides a `catch` operation to expose it. This avoids changes to the core of cohttp. The lwt-unix and mirage implementations both make use of `Lwt.fail` to carry IO errors.

This PR adds a unit-test to check that the server doesn't crash if the client closes the connection. It also adds checks to some other tests to ensure that no errors or warnings were logged during the test.

### CODE REVIEW

File: cohttp-lwt-unix/src/io.ml [hunk 1]
```diff
@@ -29,17 +35,25 @@ type conn = Conduit_lwt_unix.flow
 let src = Logs.Src.create "cohttp.lwt.io" ~doc:"Cohttp Lwt IO module"
 module Log = (val Logs.src_log src : Logs.LOG)
 
-let with_closed_handler f ~if_closed =
+let wrap_read f ~if_closed =
   (* TODO Use [Lwt_io.is_closed] when available:
      https://github.com/ocsigen/lwt/pull/635 *)
```
Comment (avsm) [inline cohttp-lwt-unix/src/io.ml]: Does this TODO make sense to implement (or delete) here?  Lwt_io.closed has been available since lwt.4.2.0

Comment (talex5) [reply cohttp-lwt-unix/src/io.ml]: Probably, but I think that should be a separate PR.

**Comment by avsm** [comment]
Tested on github and rwo's regression tests also -- thanks for this fix!

**Comment by hcarty** [comment]
Thank you for this! I think this makes #645 even more important, so these log messages can be controlled separately by the application.
